Feature add dashboard
casbin/caswaf pull request #28
Opened 2024-05-26 11:56 UTC by love98ooo

2024-05-26 11:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casbin/caswaf?pullRequest=28) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casbin/caswaf?pullRequest=28) before we can accept your contribution.<br/><hr/>**Love98** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casbin/caswaf?pullRequest=28) it.</sub>

2024-05-26 15:32 UTC, nomeguy requested changes

2024-05-26 15:32 UTC, nomeguy commented on controllers/metric.go
> +	"github.com/casbin/caswaf/object"
sort

2024-05-26 15:32 UTC, nomeguy commented on controllers/metric.go
> +	switch rangeType {
Is this same as Casibase?

2024-05-26 15:32 UTC, nomeguy commented on controllers/metric.go
> +	count, err := strconv.Atoi(c.Input().Get("count"))
util.ParseInt for everywhere

2024-05-26 15:32 UTC, nomeguy commented on web/src/DashboardPage.js
> +  renderBarChart(title, data) {
Define a JS file for each card, put them into a folder

2024-05-26 15:32 UTC, nomeguy commented on web/src/index.css
> +.ant-card {
Can we avoid global CSS?

2024-05-26 15:32 UTC, nomeguy commented on web/yarn.lock
> +echarts-for-react@^3.0.2:
Use https://registry.yarnpkg.com for everywhere

2024-05-27 12:17 UTC, love98ooo commented on controllers/metric.go
> +	switch rangeType {
They have similar functions, but different abstractions.

2024-05-28 11:35 UTC, nomeguy approved these changes

2024-05-28 11:36 UTC, merged