feat: add ip rule
casbin/caswaf pull request #46
Opened 2024-07-27 04:32 UTC by love98ooo

2024-07-27 09:09 UTC, nomeguy requested changes

2024-07-27 09:09 UTC, nomeguy commented on util/request.go
> +package util
Apache header

2024-07-27 09:09 UTC, nomeguy commented on web/src/components/IpRuleTable.js
> +        render: (text, rule, index) => (
keep record

2024-07-27 09:09 UTC, nomeguy commented on web/src/components/IpRuleTable.js
> +        render: (text, rule, index) => (
keep record

2024-07-27 09:09 UTC, nomeguy commented on web/src/components/IpRuleTable.js
> +        render: (text, rule, index) => (
keep record

2024-07-27 09:09 UTC, nomeguy commented on web/src/components/IpRuleTable.js
> +        render: (text, rule, index) => (
keep record

2024-07-27 09:09 UTC, nomeguy commented on web/src/components/IpRuleTable.js
> +            <Button style={{marginRight: "5px"}} type="primary" size="small" onClick={() => this.restore()}>{"Restore Build-in IP Rules"}</Button>
Rename all to "Restore"

2024-07-27 09:09 UTC, nomeguy commented on rule/rule_ip.go
> +		op := expression.Operator == "is in"
what's op?

2024-07-27 09:09 UTC, nomeguy commented on rule/rule_ip.go
> +		ips := strings.Split(expression.Value, " ")
GetClientIp should only return one IP address, so no for loop

2024-07-27 09:09 UTC, nomeguy commented on rule/rule_ip.go
> +			_, ipNet, err := net.ParseCIDR(ip)
This is wrong.

If contains "/", then parse as CIDR

Else if contains ":", then parse as IPv6 address

Else, parse as IPv4 address

For each parsing error, return error

2024-07-27 09:09 UTC, nomeguy commented on web/src/components/IpRuleTable.js
> +          value: "0.0.0.0/8 10.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 172.16.0.0/12 192.0.0.0/24 192.0.2.0/24 192.88.99.0/24 192.168.0.0/16 198.18.0.0/15 198.51.100.0/24 203.0.113.0/24 224.
too many as examples, so two or three is enough. Make people hard to delete them all

2024-07-27 10:15 UTC, love98ooo commented on rule/rule_ip.go
> +		op := expression.Operator == "is in"
operator (op)

2024-07-27 11:28 UTC, nomeguy commented on rule/rule_ip.go
> +		op := expression.Operator == "is in"
op should not be boolean

2024-07-27 11:29 UTC, nomeguy requested changes

2024-07-27 11:29 UTC, nomeguy commented on rule/rule_ip.go
> +		ips := strings.Split(expression.Value, " ")
Use comma to split

2024-07-28 01:30 UTC, nomeguy requested changes

2024-07-28 01:30 UTC, nomeguy commented on rule/rule_ip.go
> +				if ipNet.Contains(net.ParseIP(clientIp)) == (expression.Operator == "is in") {
check error for net.ParseIP(clientIp)

2024-07-28 01:30 UTC, nomeguy commented on rule/rule_ip.go
> +				if (ip == clientIp) == (expression.Operator == "is in") {
Never write this, expression 1 == expression 2

don't play tricks

2024-07-28 01:30 UTC, nomeguy commented on rule/rule_ip.go
> +				return false, "", fmt.Errorf("invalid ip: %s", ip)
unknown IP or CIDR format: %s

2024-07-28 01:30 UTC, nomeguy commented on web/src/components/IpRuleTable.js
> +          value: "10.0.0.0/8,127.0.0.0/8,192.0.0.0/24",
10.0.0.0/8,192.168.0.0/16

2024-07-28 15:05 UTC, nomeguy requested changes

2024-07-28 15:05 UTC, nomeguy commented on rule/rule_ip.go
> +				}
Handle switch-default like:

![image](https://github.com/user-attachments/assets/8458fe01-3f06-4afd-9f9d-cccaf8e20aa8)

2024-07-28 15:05 UTC, nomeguy commented on rule/rule_ip.go
> +				}
Handle switch-default like:

![image](https://github.com/user-attachments/assets/8458fe01-3f06-4afd-9f9d-cccaf8e20aa8)

2024-07-29 02:57 UTC, nomeguy approved these changes

2024-07-29 02:58 UTC, merged