feat: support IP rate limiting
casbin/caswaf pull request #59
Opened 2024-08-06 16:10 UTC by love98ooo

#58 

P.S. update antd to ~4.24.0

2024-08-09 09:57 UTC, nomeguy requested changes

2024-08-09 09:57 UTC, nomeguy commented on controllers/rule.go
> +	case "IpRate":
Label is "IP Rate Limiting"

2024-08-09 09:57 UTC, nomeguy commented on controllers/rule.go
> +	if len(expressions) != 1 {
Will this be zero?

2024-08-09 09:57 UTC, nomeguy commented on controllers/rule.go
> +		return errors.New("IpRate rule should have only one expression")
Better to limit this in frontend too

2024-08-09 09:57 UTC, nomeguy commented on web/src/RuleEditPage.js
> +                  {value: "IpRate", text: "IP Rate"},
Label is "IP Rate Limiting"

2024-08-09 09:57 UTC, nomeguy commented on web/src/RuleEditPage.js
> +                  title={"IP Rate"}
Label is "IP Rate Limiting"

2024-08-09 09:57 UTC, nomeguy commented on web/src/RuleEditPage.js
> +                  title={"IP Rate"}
i18n

2024-08-09 09:57 UTC, nomeguy commented on web/src/components/IpRateRuleTable.js
> +        title: "Name",
i18n

2024-08-09 09:57 UTC, nomeguy commented on web/src/components/IpRateRuleTable.js
> +        title: "Rate",
i18n

2024-08-09 09:57 UTC, nomeguy commented on web/src/components/IpRateRuleTable.js
> +        title: "Block Duration",
i18n

2024-08-09 09:57 UTC, nomeguy commented on web/src/components/UaRuleTable.js
> +            <Button style={{marginRight: "5px"}} type="primary" size="small" onClick={() => this.restore()}>{"Restore"}</Button>
Check all i18n

2024-08-09 09:57 UTC, nomeguy commented on rule/rule.go
> +		case "IpRate":
Label is "IP Rate Limiting"

2024-08-09 10:00 UTC, love98ooo commented on controllers/rule.go
> +	if len(expressions) != 1 {
It is not allowed to be zero.

2024-08-09 10:05 UTC, love98ooo commented on controllers/rule.go
> +		return errors.New("IpRate rule should have only one expression")
It has been limited in frontend.

2024-08-10 04:36 UTC, nomeguy approved these changes

2024-08-10 04:37 UTC, merged