feat: add action object
casbin/caswaf pull request #72
Opened 2024-08-28 15:23 UTC by love98ooo

Separate actions from rules as an object.

2024-08-30 13:53 UTC, nomeguy requested changes

2024-08-30 13:53 UTC, nomeguy commented on object/action.go
> +	ImmunityTimes int    `xorm:"int notnull" json:"immunityTimes"` // minutes
Let GPT give you a good English name

2024-08-30 13:53 UTC, nomeguy commented on controllers/action.go
> +		CreatedTime: time,
Copy paste from other object, don't write by yourself

2024-08-30 13:53 UTC, nomeguy commented on object/action_cache.go
> +var actionMap = map[string]*Action{}
Why action still needs actionMap? Delete all

2024-09-03 06:35 UTC, love98ooo commented on object/action.go
> +	ImmunityTimes int    `xorm:"int notnull" json:"immunityTimes"` // minutes
This is what AWS uses. I didn't make it up.

![image](https://github.com/user-attachments/assets/fea2bd6c-6cd6-4c93-96fd-7dcbc073a53c)

2024-09-03 06:35 UTC, love98ooo commented on object/action_cache.go
> +var actionMap = map[string]*Action{}
If an action updates, we need the map to make it work immediately.

2024-09-03 06:35 UTC, love98ooo commented on controllers/action.go
> +		CreatedTime: time,
![image](https://github.com/user-attachments/assets/dcb74e6d-f68c-4588-be49-87bc7a96d770)

It is copied from controller/rule.go

2024-09-05 12:31 UTC, nomeguy approved these changes

2024-09-05 12:31 UTC, merged